export const posts = [
  {
    id: 1,
    user: "Fabien",
    hasTag: "@rearwindow",
    time: "10min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 25,
    noResent: 15,
    noLikes: 45,
  },
  {
    id: 21,
    user: "Daryl",
    hasTag: "@rthethirdman",
    time: "5min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 12,
    noResent: 75,
    noLikes: 23,
  },
  {
    id: 3,
    user: "Rafael",
    hasTag: "sculpordwarf",
    time: "25min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 15,
    noResent: 11,
    noLikes: 12,
  },
  {
    id: 5,
    user: "Philippe",
    hasTag: "@rearwindow",
    time: "10min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 24,
    noResent: 36,
    noLikes: 15,
  },
  {
    id: 14,
    user: "Mustafa",
    hasTag: "@batmanbegins",
    time: "10min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 12,
    noResent: 76,
    noLikes: 75,
  },
  {
    id: 17,
    user: "میدان رسالت",
    hasTag: "@rnormanbates",
    time: "14min",
    tweet: "Proin in porta erat, ac dictum diam. Ut a est. ",
    noMessages: 25,
    noResent: 14,
    noLikes: 85,
  },
];
